"""
Daily modulation of the DM-phonon scattering rate in Al2O3 (light dark photon),
computed with PhonoDark.

This is a *driver*: it does not reimplement any PhonoDark physics. It generates
the PhonoDark input files the run needs (a numerics file and one physics file
per mass), invokes the stock ``calculator.py`` on the command line from the
PhonoDark tree, and collects the resulting HDF5 into the JSON schema 3_plot.py
consumes. The material inputs (POSCAR, FORCE_SETS, BORN) and the dark-photon
physics model are PhonoDark's own, taken from its ``inputs/`` directory -- the
generated physics file loads ``inputs/physics_model/light_dark_photon.py`` and
overrides only the DM mass list, the time list, and the threshold.

Thresholds
----------
The run uses omega_min = 1 meV and stores PhonoDark's ``diff_rate``, i.e., the
rate resolved in 1 meV energy bins, exactly mirroring the layout 1b_vpd_rate.py
writes. A higher threshold -- the 20 meV benchmark of the draft -- is obtained
downstream (3_plot.py) by summing the stored bins above it, with no new
PhonoDark run.

The four masses are run as four separate ``calculator.py`` invocations so that
results land incrementally and an interrupted run resumes where it left off
(``--force`` recomputes).

Core count
----------
``--nproc`` sets the number of MPI ranks (jobs in flight) and ``--threads`` the
number of BLAS/OpenMP threads *within* each rank. The default is the fully
serial ``--nproc 1 --threads 1``; this is the configuration the draft's timing
table compares against a 1b_vpd_rate.py run with NUMBA_NUM_THREADS=OMP_NUM_THREADS=1.
The chosen values are recorded in pd_timing.json.

Pipeline:   1a_vpd_project.py  ->  1b_vpd_rate.py  ->  2_pd.py  ->  3_plot.py
Outputs:    output/modulation/pd_binned.json
            output/modulation/pd_timing.json
            output/modulation/pd_runs/   (generated inputs + raw PhonoDark HDF5)

Run (phonodark environment):
    python -u scripts/reproduce_paper/modulation/2_pd.py --nproc 1 --threads 1
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import h5py
import numpy as np

# Location of the PhonoDark checkout. Override with yours.
PHONODARK_DIR = Path(
    os.path.expanduser(os.environ.get("PD_DIR", ""))
)

# Override with the PD_PYTHON / PD_MPIRUN environment variables with yours.
PD_PYTHON = Path(
    os.environ.get(
        "PD_PYTHON", os.path.expanduser("")
    )
)
PD_MPIRUN = Path(
    os.environ.get(
        "PD_MPIRUN", os.path.expanduser("")
    )
)

# phonopy API compat shim
# PD_PYTHONPATH_SHIM = os.environ.get(
#     "PD_PYTHONPATH_SHIM", ""
# )

# Fail early with a clear message if the PhonoDark side is not configured:
# the import below already needs the checkout on sys.path.
if not (PHONODARK_DIR / "calculator.py").is_file():
    sys.exit(
        "PhonoDark checkout not found: set the PD_DIR environment variable "
        f"to your PhonoDark directory (got '{PHONODARK_DIR}')."
    )

sys.path.insert(0, str(PHONODARK_DIR))
import src.constants as const  # noqa: E402  (needs PhonoDark on sys.path)

# --- Benchmark configuration (matches 1b_vpd_rate.py) ---
MASSES_KEV = [50, 100, 500, 1000]
N_TIMES = 24
# eV; bins start here, 20 meV extracted in 3_plot.py
ENERGY_THRESHOLD = 1e-3
ENERGY_BIN_WIDTH = 1e-3  # eV

# PhonoDark momentum mesh (draft: 100 x 25 x 25, q_cut, special mesh)
N_A, N_B, N_C = 100, 25, 25
POWER_A, POWER_B, POWER_C = 1, 1, 1
SPECIAL_MESH = True
Q_CUT = True
N_DW = 20

# PhonoDark's own Al2O3 material input and light dark photon model.
MATERIAL_INPUT = PHONODARK_DIR / "inputs" / "material" / "Al2O3" / "Al2O3.py"
BASE_PHYSICS_MODEL = PHONODARK_DIR / "inputs" / "physics_model" / "light_dark_photon.py"

# Light dark photon:  F_DM ~ q^-2,  q0 = alpha m_e.  Kept consistent with the
# constants PhonoDark itself used for the run.
Q0_FDM = const.ALPHA_EM * const.M_ELEC
MASS_SM = const.M_ELEC

OUT_JSON = "pd_binned.json"
TIMING_JSON = "pd_timing.json"


def numerics_source(output_folder: Path) -> str:
    """PhonoDark numerics input file for this benchmark."""
    return f'''"""Generated by 2_pd.py -- Al2O3 daily-modulation benchmark."""

io_parameters = {{
    "output_folder": r"{output_folder}",
    "output_filename_extra": "",
}}

numerics_parameters = {{
    "n_a": {N_A},
    "n_b": {N_B},
    "n_c": {N_C},
    "power_a": {POWER_A},
    "power_b": {POWER_B},
    "power_c": {POWER_C},
    "n_DW_x": {N_DW},
    "n_DW_y": {N_DW},
    "n_DW_z": {N_DW},
    "energy_bin_width": {ENERGY_BIN_WIDTH!r},
    "q_cut": {Q_CUT},
    "special_mesh": {SPECIAL_MESH},
}}
'''


def physics_source(mass_keV: int) -> str:
    """PhonoDark physics-model input: the shipped light dark photon model with
    only the mass list, time list, and threshold overridden."""
    times = [float(t) for t in range(N_TIMES)]
    return f'''"""Generated by 2_pd.py -- PhonoDark's light dark photon model,
with the DM mass list, time list, and threshold overridden. Every other physics
choice (c_dict, c_dict_form, screening, Fmed_power, power_V, special_model,
VDF) is taken unchanged from the shipped input file."""

from importlib import util as _util

_spec = _util.spec_from_file_location("_base_dark_photon", r"{BASE_PHYSICS_MODEL}")
_base = _util.module_from_spec(_spec)
_spec.loader.exec_module(_base)

include_screen = _base.include_screen
c_dict = _base.c_dict
c_dict_form = _base.c_dict_form
vdf_model = _base.vdf_model

physics_parameters = dict(_base.physics_parameters)
physics_parameters["threshold"] = {ENERGY_THRESHOLD!r}
physics_parameters["times"] = {times!r}

input_masses = [{float(mass_keV * 1e3)!r}]
dm_properties_dict = dict(_base.dm_properties_dict)
dm_properties_dict["mass_list"] = input_masses
'''


def thread_env(threads: int) -> dict:
    """Environment for the calculator.py subprocess, pinned to `threads`.

    mpirun forwards these to every rank. The set covers the common BLAS
    backends, so the setting holds regardless of how numpy was built.
    """
    env = os.environ.copy()
    for var in (
        "OMP_NUM_THREADS",
        "MKL_NUM_THREADS",
        "OPENBLAS_NUM_THREADS",
        "VECLIB_MAXIMUM_THREADS",
        "NUMEXPR_NUM_THREADS",
    ):
        env[var] = str(threads)
    # if PD_PYTHONPATH_SHIM:
    #     existing = env.get("PYTHONPATH", "")
    #     env["PYTHONPATH"] = (
    #         PD_PYTHONPATH_SHIM + os.pathsep + existing
    #         if existing
    #         else PD_PYTHONPATH_SHIM
    #     )
    return env


def run_one_mass(mass_keV: int, run_dir: Path, nproc: int, threads: int, force: bool):
    """Invoke stock calculator.py for one mass over all N_TIMES times.

    Stock calculator.py rebuilds the momentum mesh per (mass, time) job from
    vE_vec(t). Do not "optimize" this by reusing the t = 0 mesh across the 24
    hours: that is ~20x faster but biased low by up to ~1% near the modulation
    minimum at the lightest mass (the reused mesh misses modes that become
    kinematically accessible as vE rotates).

    Returns (hdf5_path, wall_seconds_or_None). wall is None when the existing
    output was reused.
    """
    phys_name = f"pdbench_phys_m{mass_keV}"
    num_name = "pdbench_num"
    phys_path = run_dir / f"{phys_name}.py"
    num_path = run_dir / f"{num_name}.py"
    phys_path.write_text(physics_source(mass_keV))
    num_path.write_text(numerics_source(run_dir))

    # calculator.py: material + '_' + phys_mod + '_' + num_mod + extra + '.hdf5'
    out_h5 = run_dir / f"Al2O3_{phys_name}_{num_name}.hdf5"

    if out_h5.exists() and not force:
        try:
            with h5py.File(out_h5, "r") as f:
                if len(f["data/diff_rate"]) == N_TIMES:
                    print(f"  reusing existing {out_h5.name} (--force to redo)")
                    return out_h5, None
        except (OSError, KeyError):
            pass
        print(f"  {out_h5.name} incomplete -- recomputing")

    calc = [
        str(PD_PYTHON), "-u", "calculator.py",
        "-m", str(MATERIAL_INPUT),
        "-p", str(phys_path),
        "-n", str(num_path),
    ]
    # At one rank, invoke calculator.py directly rather than through mpirun.
    cmd = calc if nproc == 1 else [str(PD_MPIRUN), "-n", str(nproc)] + calc
    print(f"  $ {' '.join(cmd)}", flush=True)
    print(f"  ({threads} BLAS/OpenMP thread(s) per rank)", flush=True)
    t0 = time.time()
    proc = subprocess.run(cmd, cwd=str(PHONODARK_DIR), env=thread_env(threads))
    wall = time.time() - t0
    if proc.returncode != 0:
        raise RuntimeError(
            f"calculator.py failed for {mass_keV} keV (exit {proc.returncode})"
        )
    if not out_h5.exists():
        raise RuntimeError(f"calculator.py produced no output at {out_h5}")
    print(f"  {mass_keV} keV done in {wall / 60:.1f} min", flush=True)
    return out_h5, wall


def read_diff_rate(h5_path: Path):
    """diff_rate[t] for the single mass in this file, as a list of 1D arrays.

    PhonoDark stores data/diff_rate/<time_index>/<mass_index>; each file here
    holds one mass, so there is a single mass key. Also returns the stored total
    rate per time for a consistency check.
    """
    per_time, totals = [], []
    with h5py.File(h5_path, "r") as f:
        for t in range(N_TIMES):
            grp = f[f"data/diff_rate/{t}"]
            key = sorted(grp.keys())[0]
            per_time.append(np.asarray(grp[key], dtype=float))
            totals.append(float(np.asarray(f[f"data/rate/{t}/{key}"], dtype=float)))
    return per_time, totals


def main() -> None:
    ap = argparse.ArgumentParser(description="PhonoDark modulation run")
    ap.add_argument("--nproc", type=int, default=1, help="MPI ranks (default 1)")
    ap.add_argument(
        "--threads",
        type=int,
        default=1,
        help="BLAS/OpenMP threads per rank (default 1, i.e., single core)",
    )
    ap.add_argument("--masses", type=int, nargs="+", default=MASSES_KEV)
    ap.add_argument("--force", action="store_true", help="ignore existing HDF5")
    args = ap.parse_args()

    # The PhonoDark checkout was validated at import time; check the
    # executables the run itself needs.
    if not PD_PYTHON.is_file():
        sys.exit(
            "PhonoDark python not found: set the PD_PYTHON environment variable "
            f"to the python executable of your PhonoDark environment "
            f"(got '{PD_PYTHON}')."
        )
    if args.nproc > 1 and not PD_MPIRUN.is_file():
        sys.exit(
            "mpirun not found: set the PD_MPIRUN environment variable "
            f"to the mpirun of your PhonoDark environment (got '{PD_MPIRUN}')."
        )

    out_dir = Path(__file__).resolve().parents[3] / "output" / "modulation"
    run_dir = out_dir / "pd_runs"
    run_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("PhonoDark (stock calculator.py) - Al2O3 light dark photon")
    print(f"  masses = {args.masses} keV,  {N_TIMES} times,  mesh {N_A}x{N_B}x{N_C}")
    print(
        f"  omega_min = {ENERGY_THRESHOLD * 1e3:g} meV,"
        f"  bins = {ENERGY_BIN_WIDTH * 1e3:g} meV"
    )
    print(
        f"  MPI ranks = {args.nproc},  threads/rank = {args.threads}"
        f"  ->  {args.nproc * args.threads} core(s)"
    )
    print(f"  material : {MATERIAL_INPUT}")
    print(f"  model    : {BASE_PHYSICS_MODEL}")
    print("=" * 70, flush=True)

    diff_by_mass, timing = {}, {}
    t_start = time.time()
    for mass_keV in args.masses:
        print(f"\n{'=' * 50}\n  m_chi = {mass_keV} keV\n{'=' * 50}", flush=True)
        h5_path, wall = run_one_mass(
            mass_keV, run_dir, args.nproc, args.threads, args.force
        )
        per_time, totals = read_diff_rate(h5_path)

        # diff_rate must sum to the stored total rate, time by time.
        for t, (d, tot) in enumerate(zip(per_time, totals)):
            if tot != 0.0 and abs(d.sum() / tot - 1.0) > 1e-9:
                raise RuntimeError(
                    f"diff_rate does not sum to total_rate at {mass_keV} keV, t={t}"
                )
        diff_by_mass[mass_keV] = per_time
        if wall is not None:
            timing[str(mass_keV)] = {
                "wall_sec": round(wall, 1),
                "n_jobs": N_TIMES,
                "nproc": args.nproc,
                "threads_per_rank": args.threads,
                "cores": args.nproc * args.threads,
                "sec_per_job_effective": round(wall * args.nproc / N_TIMES, 1),
            }

        mod = np.array([d.sum() for d in per_time])
        rel = (mod - mod.mean()) / mod.mean() * 100.0
        print(
            f"  rate(t=0) = {mod[0]:.4e}"
            f"   mod: [{rel.min():+.3f}%, {rel.max():+.3f}%]",
            flush=True,
        )

    total_wall = time.time() - t_start

    # Pad every (mass, time) to a common bin count: the number of bins depends
    # on the kinematic maximum, which varies with mass and time.
    n_bins = max(len(d) for per_time in diff_by_mass.values() for d in per_time)
    padded = {}
    for m, per_time in diff_by_mass.items():
        arr = np.zeros((n_bins, N_TIMES))
        for t, d in enumerate(per_time):
            arr[: len(d), t] = d
        padded[m] = arr

    thr, width = float(ENERGY_THRESHOLD), float(ENERGY_BIN_WIDTH)
    payload = {
        "code": "PhonoDark",
        "code_mode": "(stock calculator.py, per-time momentum mesh)",
        "material": "Al2O3",
        "model": "light_dark_photon",
        "masses_keV": list(args.masses),
        "n_times": N_TIMES,
        "energy_threshold_meV": thr * 1e3,
        "energy_bin_width_meV": width * 1e3,
        "bin_lower_edges_meV": [(thr + b * width) * 1e3 for b in range(n_bins)],
        "q0_fdm_eV": Q0_FDM,
        "mass_sm_eV": MASS_SM,
        "params": {
            "mesh": [N_A, N_B, N_C],
            "q_cut": Q_CUT,
            "special_mesh": SPECIAL_MESH,
            "n_DW": N_DW,
            "material_input": str(MATERIAL_INPUT),
            "physics_model_base": str(BASE_PHYSICS_MODEL),
        },
        # binned_rate[mass] has shape (n_bins, n_times): PhonoDark's diff_rate,
        # the total_rate contribution per 1 meV energy bin per time. 3_plot.py
        # sums the bins above any threshold and converts to rate.
        "binned_rate": {str(m): padded[m].tolist() for m in args.masses},
    }
    out_path = out_dir / OUT_JSON
    out_path.write_text(json.dumps(payload))
    print(f"\nStored energy-binned rate -> {out_path}")

    if timing:
        timing["total_wall_sec"] = round(total_wall, 1)
        timing["nproc"] = args.nproc
        timing["threads_per_rank"] = args.threads
        timing["cores"] = args.nproc * args.threads
        timing["note"] = (
            "wall_sec is per mass over all times on nproc MPI ranks with "
            "threads_per_rank BLAS/OpenMP threads each; "
            "sec_per_job_effective = wall_sec * nproc / n_jobs is the "
            "per-(mass, time) job cost. With nproc = threads_per_rank = 1 the "
            "run is single-core and wall times are directly comparable to "
            "1b_vpd_rate.py run under NUMBA_NUM_THREADS=OMP_NUM_THREADS=1."
        )
        (out_dir / TIMING_JSON).write_text(json.dumps(timing, indent=2))
        print(f"Timing -> {out_dir / TIMING_JSON}")
        print(
            f"Total wall clock: {total_wall / 60:.1f} min on "
            f"{args.nproc} rank(s) x {args.threads} thread(s)"
        )
    print("Next: 3_plot.py (vectorphonodark env).")


if __name__ == "__main__":
    main()
